# Generated by Django 2.2.1 on 2019-05-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0002_auto_20190507_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='calle',
            name='modelocalle',
            field=models.ManyToManyField(related_name='callemodelo', through='ciudad.ModeloCalle', to='ciudad.Modelo'),
        ),
        migrations.AddField(
            model_name='hora',
            name='disponible',
            field=models.ManyToManyField(related_name='disponible', through='ciudad.Disponible', to='ciudad.ParkingModelo'),
        ),
        migrations.AddField(
            model_name='hora',
            name='trafico',
            field=models.ManyToManyField(related_name='trafico', through='ciudad.Trafico', to='ciudad.ModeloCalle'),
        ),
        migrations.AddField(
            model_name='parking',
            name='parkmodelo',
            field=models.ManyToManyField(related_name='parkingmodelo', through='ciudad.ParkingModelo', to='ciudad.Modelo'),
        ),
        migrations.AlterField(
            model_name='disponible',
            name='hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horadisponible', to='ciudad.Hora'),
        ),
        migrations.AlterField(
            model_name='modelocalle',
            name='idcalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idcallemodelocalle', to='ciudad.Calle'),
        ),
        migrations.AlterField(
            model_name='modelocalle',
            name='idmodelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idmodelomodelocalle', to='ciudad.Modelo'),
        ),
        migrations.AlterField(
            model_name='parkingmodelo',
            name='idmodelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idmodeloparkingmodelo', to='ciudad.Modelo'),
        ),
        migrations.AlterField(
            model_name='parkingmodelo',
            name='idparking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idparkingparkingmodelo', to='ciudad.Parking'),
        ),
        migrations.AlterField(
            model_name='trafico',
            name='hora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horatrafico', to='ciudad.Hora'),
        ),
    ]
